add europe ccs2 request
Hacksore/bluelinky pull request #283
Opened 2024-09-27 10:01 UTC by arteck

2024-09-28 13:03 UTC, Hacksore requested changes
We can also remove all he files from `dist/` that were committed too.

2024-09-28 13:03 UTC, Hacksore commented on src/vehicles/european.vehicle.ts
> +      const ccs2Response = this.updateRates(
This means we'd do one request for the old endpoint and another on for CCS2, do we want that?

I'm pretty out of the loop regarding the new API.

2025-02-07 09:54 UTC, MihaiINW commented
@arteck could you share some information about how you managed to discover this new API endpoint? I would like to make an extension that allows for controlling the vehicle to load (V2L) capability and for that I need to find the proper endpoint and the request body shape.

2025-02-08 20:14 UTC, arteck commented
> @arteck could you share some information about how you managed to discover this new API endpoint? I would like to make an extension that allows for controlling the vehicle to load (V2L) capability and for that I need to find the proper endpoint and the request body shape.

lol.. google helps...and other GIT repos

2025-04-10 07:05 UTC, bausi2k commented
seems to be related to my issue: https://github.com/Hacksore/bluelinky/issues/287

2025-04-13 20:05 UTC, philipptrenz commented
Also affects the Kia EV3, can we push that forward? Need a hand @arteck?

2025-04-15 19:19 UTC, philipptrenz commented
> Where are we at the moment regarding the CCS2 endpoints?

Hi @PierreLevres, I made good progress for the car status, see #290.

2025-05-03 16:34 UTC, philipptrenz commented
@Hacksore As #290 was a duplicate of this and is now merged, this one can be closed.

2025-05-03 16:50 UTC, closed without merging